# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  

lane :app do
    xcbuild(
        workspace: "weatherApp.xcworkspace",
        scheme: "weatherApp",
        configuration: "Debug",
        xcargs: "-sdk iphonesimulator SYMROOT='/var/tmp/'"
    )
end


  lane :test do
     run_tests(workspace: "weatherApp.xcworkspace",
            devices: ["iPhone 7 Plus", "iPad Air"],
            scheme: "weatherApp")
     end
end
